@startuml
left to right direction
skinparam packageStyle rectangle

' Estilos personalizados para coherencia visual
skinparam classAttributeIconSize 8
skinparam classFontSize 16
skinparam classFontName "Arial"
skinparam classBorderColor #212837
skinparam classHeaderFontColor #FFFFFF
skinparam classHeaderBackgroundColor #8BB9E6
skinparam classArrowColor #6E95C2
skinparam linetype ortho

actor Administrador

rectangle "Casos de uso para Gestionar membresía" {
    usecase "CU.1.1\nRegistrar\nmembresía" as CU11
    usecase "CU.1.2\nActualizar\nmembresía" as CU12
    usecase "CU.1.3\nVisualizar\nmembresías" as CU13
    usecase "CU.1.3.1\nVisualizar datos\ncompletos de\nun usuario" as CU131
}

Administrador --> CU11
Administrador --> CU12
Administrador --> CU13

CU13 --> CU131 : <<include>>

note right of CU131
  • Datos de anamnesis
  • Asistencia al gimnasio
end note

@enduml
