@startuml
class Person{

}
class Customer{

}
class User{

}
class Anamnesis{

}
class Detail{

}
class Membership{

}
class TrainingPlan{

}
class Rutine{

}
class Exercise{

}
class Sesion{

}
class Admin{

}
class Asistant{

}
interface IProduct{

}
class EdibleProduct{

}
class ClothingProduct{

}
interface Ifactory{

}
class FactoryEdibleProduct{

}
class Factory
@enduml